### ISSUE TITLE
subscription doesn't work on idle alert

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#117]
1. Open "Set Alerts" on datapoint and choose checkbox "Idle alert enabled"
2. Create subscription with "Any alert"
3. Subcription will never be triggered

P.S. If I choose not only "Idle alert enabled" chechbox, but "Low alert enabled" in addition (thus I have two choosen checkboxes) then subscription works when datapoint is in "idle alert" state.

**Comment by bsautner** [comment]
fixed in 4.0.0
