### ISSUE TITLE
/service/v3/rest/me link doesn't work (server 3.9.56)

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#130]
When I press "Browse REST API" from web UI, I get the following:

HTTP ERROR 400

Problem accessing /service/v3/rest/me. Reason:

    Missing request header 'Authorization' for method parameter of type String

**Comment by bsautner** [comment]
you need to install a browser plugin that adds a the auth header - when you click on the link you go to a new page without credentials

Authorization : Basic test@example.com:password

I also install a json prettify plugin for chrome

**Comment by nikolchina** [comment]
What plugin do you use for auth header in chrome?

**Comment by bsautner** [comment]
I use ModHeader and JsonView - JsonView will make the json response look readable and the links clickable.  Don't forget to turn ModHeader off when done - you'll have trouble with other websites.

**Comment by nikolchina** [comment]
Thanks
