### ISSUE TITLE
No Data showing

### ISSUE THREAD

**Issue by ericklil** [bsautner/com.nimbits#17]
Hello there Ben,

I am pretty new to this but hope to use this service professionally when testing pans out. 

I am working to feed data to Nimbits from an Arduino, getting the right feedback from this end however nothing seems to log on the server. Ultimately I would like to use MQTT however I am having issues to set that up as I believe the available code may be "old" and i am too "new" to recognize where the issues lay. I would be very grateful for any support.

Erick Oeseburg
poolworks@mac.com

**Comment by bsautner** [comment]
hopefully things are working better for you today :-)
