### ISSUE TITLE
Couldn't set low alarm and disable idle alarm

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#171]
When webhook triggers our server side, we change enabled alarms on datapoint and then send the response to nimbits. Seems, that this piece of code works fine
**datapoint.setLowAlarmOn(false);
datapoint.setIdleAlarmOn(true);
nimbitsClient.addPoint(nimbitsClient.getMe(), datapoint);**
but this one does not:
**datapoint.setLowAlarmOn(true);
datapoint.setIdleAlarmOn(false);
nimbitsClient.addPoint(nimbitsClient.getMe(), datapoint);**

after calling the last one, on web UI I can observe, that idle alarm is enabled and low alarm is not, but idle subscription doesn't work. But after I press the button "submit" on "set alerts" screen (idle alert checkbox is active, I don't change anything, just press the button), low alarm becomes active. It looks like stuck transaction.

**Comment by bsautner** [comment]
i'll take a look

**Comment by bsautner** [comment]
I'm having trouble reproducing this.  I wrote this test that flips alarms in every possible configuration: 
[https://github.com/bsautner/com.nimbits/blob/master/nimbits_io/src/itest/java/com/nimbits/it/AlarmTest.java](url)

I also did it manually.  Can you send me some screen shots or any more info so I can reproducing it?

**Comment by nikolchina** [comment]
It can be reproduce when webhook is triggered. Webhook sends request and before receiving the response, we try to set low alarm and disable idle alarm. But after webhook recieves the response it returns low alarm and idle alarm back to previous status.

**Comment by nikolchina** [comment]
I have datapoint with idle alert enabled, when it is triggered, webhook sends me notification and before sending the response you can try to sleep the current thread for the 20 seconds. When it sleeps, try to disable idle alert and enable low alert (you can use UI or java code). Check alarm statuses after thread is awake and response is received by webhook.

**Comment by bsautner** [comment]
Ok - so when an idle alert is processed, the system sets a flag that the subscriptions were processed.  That way, the idle alarm only fires once.  What's happening is the process gets a copy of the point,  does the subscriptions and when done, updates the point with the sent flag.  This means any changes to the point that happen while subscriptions are being processed will be overwritten.   I understand what's happening and can fix it so changes to a point aren't overwritten

**Comment by nikolchina** [comment]
How many times webhook triggers the URL? My thread was waiting for 20 seconds before sending the response and I can see, that each 5 seconds webhooks triggers URL until it gets the response. Thus, I received 5 notifications from nimbits. Is it as designed  behaviour?

**Comment by bsautner** [comment]
there is a background task that runs ever 5 seconds to process idle points.  it looks for idle points that haven't been flagged as processed.  since your thread is deadlocking for 20 seconds, the points never get flagged and keep getting processed.  I'm looking as the design of this entire process - i'll mark idle points processed before executing the webhooks, for example.
