### ISSUE TITLE
API V3 REST POST Snapshot without timestamp specified in JSON inputs '0' in TIMESTAMP field

### ISSUE THREAD

**Issue by 8rody** [bsautner/com.nimbits#180]
API V3 REST POST Snapshot without timestamp specified in JSON inputs '0' in TIMESTAMP field

e.g.

JSON Data Example inserts "0" into mysqlDB/nimbits/VALUESTORE/timestamp field:
`{ "d":10.0, "dx":"", "st":"", "m":"" }`

Which, is of course, is displaced as 01/01/1970 (Linux Epoch)

As a result, the POST to Snapshot does not use the snapshot time function per se.

Additionally;

JSON Data Example inserts "0" into mysqlDB/nimbits/VALUESTORE/timestamp field:
`{ "d":10.0, "t":null, "dx":"", "st":"", "m":"" }`

**Comment by bsautner** [comment]
nimbits used to check for null in "t" and set it to the current time - it's probably getting defaulted to 0 instead of null and not being set.  I'll check it out - thanks for your kind email 👍

**Comment by 8rody** [comment]
Tired `{.. "t":null, ..}` in the JSON data array, to trigger the boolean function System.currentTimeMillis() in ValueStore.java.

All to no avail. '0' gets inserted as a timestamp.

**Comment by bsautner** [comment]
i've been pulling as many lines of code that either create a Date() object or instance of Calendar in favor of using a `long` primitive which is much faster - that's where this bug came from. Thanks!
