### ISSUE TITLE
Expire days feature doesn't work

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#184]
Look at the /com/nimbits/server/data/DataProcessor.java
there is a multiplication of two int values, which causes to overflow (getExpireTime method)
There should be "<=" insted of ">=" in the method ignoreDataByExpirationDate

**Comment by bsautner** [comment]
what value are you setting the points expire time too?

**Comment by nikolchina** [comment]
when I set 2 days, there is no overflow and method ignoreDataByExpirationDate always returns true and value is ignored, it will return false only if value timestamp will be 2 days less then System.currentTimeMillis(). When I set 90 days, then overflow happens and the value 84600*1000*90 becomes -813934592. Then value will be ignored only if the timestamp is more than System.currentTimeMillis() + 813934592
