### ISSUE TITLE
I can not enter nimbits login by browser

### ISSUE THREAD

**Issue by frazier120** [bsautner/com.nimbits#190]
Hello everyone. I install nimbits on ubuntu 14.04 by "sudo apt-get install nimbits". but when I use "localhost:8080" to access nimbits home page, it response 404 not found. 
Then I check log after I start nimbits service and find this fail :
"Dec 08, 2016 5:14:22 PM com.nimbits.server.process.cron.SystemTaskExecutor$SystemTask run
INFO: DP:: com.nimbits.server.process.cron.SystemTaskExecutor$SystemTask false "
How can I solve it ? 
Thanks.

**Comment by bsautner** [comment]
Hi

I discontinued the debian package install a while ago.  Your bet bet is to
install from source.  I do it this way all of the time and it works well:

https://github.com/bsautner/com.nimbits/wiki/Install:-Build-from-source

All you need is a fresh ubuntu server and follow the steps at the top of
that wiki to run the setup.sh script

Let me know how it goes!

Ben

**Comment by frazier120** [comment]
Hi bsautner. 
I use install.sh to install nimbits and use "localhost:8080" to access nimbits home page.
I just see tomcat8 home page which mean install tomcat8 success. 
I can't see nimbits home page. 
why?

**Comment by bsautner** [comment]
after you deploy a nimbits.war to a tomcat folder, it's context is going to be whatever the war file name is - so nimbits.war will be on localhost:8080/nimbits  and foobar.war will be on localhost:8080/foobar.  if you rename the war to root.war, it will be on the  base context localhost:8080
