### ISSUE TITLE
Is there any webservice api or script to Manage user account?

### ISSUE THREAD

**Issue by frazier120** [bsautner/com.nimbits#191]
Hi, as the title , there is a pressing need to do things  like register , change password  and delete account etc, 
Is there any possible way to do that? webservice , db script or anything else 
Please offer some approaches.
( I use old nimbits version, nimbits api version 2 )
Thnaks a lot

**Comment by bsautner** [comment]
you can now delete, add, remove and reset passwords for users via the v3 api - client samples are in the client docs: https://github.com/bsautner/com.nimbits/wiki/Client:-nimbits.io-library-overview
