### ISSUE TITLE
nimbits server requests wrong url for webhook notification

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#202]
Instead of calling
http://auto-dev-mera.mera.ooma.com:8083/hms/webhook/on/user/44 or this one
http://auto-dev-mera.mera.ooma.com:8083/hms/webhook/on/user/21

it is always requesting the wrong url, when it is necessary to call the above ones
http://auto-dev-mera.mera.ooma.com:8083/hms/webhook/on/user/25

**Comment by bsautner** [comment]
can you email me the details on the two webhooks - ideally the record in sqllite that contains them in WEBHOOKENTITY TABLE?

**Comment by bsautner** [comment]
fixed in 4.1.1
