### ISSUE TITLE
mvn clean install error

### ISSUE THREAD

**Issue by fang0154** [bsautner/com.nimbits#203]
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/sbap/com.nimbits/nimbits_server/pom.xml of /home/sbap/com.nimbits/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.nimbits:nimbits-parent:4.1.1-SNAPSHOT (/home/sbap/com.nimbits/pom.xml) has 1 error
[ERROR]     Child module /home/sbap/com.nimbits/nimbits_server/pom.xml of /home/sbap/com.nimbits/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by bsautner** [comment]
there is a defect in the master branch we're working out - stand by :)

**Comment by bsautner** [comment]
should be working now
