### ISSUE TITLE
findUser(String username) doesn't work

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#205]
findUser() method returns
Exception in thread "main" retrofit.RetrofitError: 404 Not Found
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy20.findUser(Unknown Source)
	at com.nimbits.client.io.Nimbits.findUser(Nimbits.java:404)

so when we try to remove user, we are not able to do it because of this exeption, when nimbits tries to find this user

**Comment by bsautner** [comment]
when we fixed #201 we ensured only entities (including users) that belonged to the user could be accessed through the Nimbits.find() methods.  Since you're probably using an admin user id `findUser` is returning a 404. 

We'd want to add a Nimbits.deleteUser(String email) that an admin user can use. I can add that by tomorrow if needed.

As a workaround, it is safe to run this SQL query against the database

`delete FROM nimbits.USERENTITY where name="test@example.com";`

**Comment by bsautner** [comment]
didn't mean to close it :)

**Comment by bsautner** [comment]
can you let me know if you'll be able to import a new version of the client jar v4.1.2 from jcenter with a new admin methods getUser(String email) and deleteUser(String email) or if you need the findUser and deleteEntity methods to work across accounts so an admin can use those methods.  I'd prefer to give you the new admin methods.

**Comment by nikolchina** [comment]
I am able to download only 4.1.1 nimbits_io version, not 4.1.2
and 4.1.1 doesn't contain such methods

what do you mean by "admin methods", is it another entity for admin, not Nimbits object with admin credentials as it was before?

**Comment by bsautner** [comment]
sorry, i mean i'll add those methods and release v4.1.2 for your use right away.

When you create the Nimbits object you add credentials to the builder.  The user you have been using is the admin of the system with admin privileges on the Nimbits Server.  You can create a Nimbits object using any email and password to just access that user's info.

**Comment by bsautner** [comment]
I'm going to release a build of 4.1.2 that has nimbits.getUser(email) and nimbits.deleteUser(email) - if you create a nimbits object using admin credentials they'll work on any user.
