### ISSUE TITLE
when I try to add already existing user, nimbits fails with retrofit exception

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#207]
Exception in thread "main" retrofit.RetrofitError: 500 Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy20.addUser(Unknown Source)
	at com.nimbits.client.io.Nimbits.addUser(Nimbits.java:110)

Previously nimbits wrapped such errors with NimbitsClientException, but now it fails with retrofit error

**Comment by nikolchina** [comment]
the same situation with adding other types of existing entities

**Comment by bsautner** [comment]
NimbitsClientException was obscuring the actual error which is the server error - in this case a server error when trying to add a duplicate (the next release will return a `403 Conflict` instead of a 500.  It's prefered that we return the actual server error.  Can you change your client code to catch the retrofit error instead of NimbitsClientException ?

**Comment by nikolchina** [comment]
You can return actual server error, but wrap all these retrofit exceptions into your client library exceptions. You can build your exceptions adding needed fields to it, such as messages, statuses or whatever you want. You can build hierarchy of your client exceptions. And this would look better actually. With retrofit library you make users of your client library be dependent on the implementation you use. In future you can use another rest library, not retrofit, and your client (client of nimbits_io) will have to change their code to catch something else instead of retrofit exceptions.

**Comment by bsautner** [comment]
makes sense - we can catch retrofit and throw a new custom runtime exception - let me know if this is blocking production for you and i'll make the change - otherwise it'll be in the next weekly build

**Comment by nikolchina** [comment]
You can introduce it later, so far I haven't met any blocking issues related to it.

**Comment by bsautner** [comment]
4.1.5 will throw a nimbits client exception
