### ISSUE TITLE
POST not working on series

### ISSUE THREAD

**Issue by imwebgefunden** [bsautner/com.nimbits#31]
In the Documentation:
"The series web service will response to a GET request with an array of Value objects for one specific data point. You can also POST many values to many different points by providing a JSON Array of Points, each with an Array of Values. See below for the json syntax."

Example code for arduino is in com.nimbits / nimbits_arduino / samples / batch_demo / batch_demo.ino.

But the implementation in com.nimbits / nimbits-server / src / main / java / com / nimbits / server / api / impl / SeriesServletImpl.java don't handle post-request.

I've got the following error: "Error: HTTP method POST is not supported by this URL" if I try to post something to the series-URL.

**Comment by bsautner** [comment]
new docs added to post to the series api

http://nimbits.com/howto_api_series.jsp
