### ISSUE TITLE
A faster Blob reading method,... maybe

### ISSUE THREAD

**Issue by mwehr** [bsautner/com.nimbits#36]
Hi Benjamin,

What do you think about changing the "private String readFile(String fn)" to
```java
private String readFile(String fn) throws IOException {
        try {
            return new String(readAllBytes(get(fn)));
        }catch (Exception ex){
            return "";
        }
}
```

This could give a bit extra performance, I think.

regards

Mario

**Comment by bsautner** [comment]
we're using FileUtils.readFileToString  for servers and Google's cloud storage api for cloud
